set( APPLICATION_SHORTNAME  "cernbox" )
set( APPLICATION_NAME       "CERNBox" )
set( APPLICATION_EXECUTABLE "cernbox"        )
set( APPLICATION_DOMAIN     "cern.ch/cernbox"          )
set( APPLICATION_VENDOR     "CERN"     )
set( APPLICATION_REV_DOMAIN "ch.cernbox.client" )
set( THEME_CLASS            "CernBoxTheme"        )
set( THEME_INCLUDE          "${OEM_THEME_DIR}/cernboxtheme.h" )
set( WIN_SETUP_BITMAP_PATH  "${OEM_THEME_DIR}/installer/nsi" )
#set( APPLICATION_LICENSE    "${OEM_THEME_DIR}/license.txt" )
set( APPLICATION_UPDATE_URL "https://updates.owncloud.com/client/" CACHE string "URL for updater" )
